spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    spring.jpa.database : h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true 이건, System.out.println으로 나오는거라 지양.
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug